### ISSUE TITLE
wlroots interface out of date?

### ISSUE THREAD

**Issue by r4dr3fr4d** [flacjacket/pywlroots#10]
Upon trying to run the tiny wm:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/builds/pywlroots/tiny/__main__.py", line 15, in <module>
    from wlroots.backend import Backend
  File "/home/user/builds/pywlroots/wlroots/backend.py", line 9, in <module>
    from wlroots.wlr_types.input_device import InputDevice
  File "/home/user/builds/pywlroots/wlroots/wlr_types/__init__.py", line 5, in <module>
    from .cursor import Cursor  # noqa: F401
  File "/home/user/builds/pywlroots/wlroots/wlr_types/cursor.py", line 9, in <module>
    from .input_device import InputDevice, InputDeviceType
  File "/home/user/builds/pywlroots/wlroots/wlr_types/input_device.py", line 6, in <module>
    from .keyboard import Keyboard
  File "/home/user/builds/pywlroots/wlroots/wlr_types/keyboard.py", line 33, in <module>
    class KeyState(enum.IntEnum):
  File "/home/user/builds/pywlroots/wlroots/wlr_types/keyboard.py", line 34, in KeyState
    KEY_RELEASED = lib.WLR_KEY_RELEASED
AttributeError: cffi library 'wlroots._ffi' has no function, constant or global variable named 'WLR_KEY_RELEASED'
```

**Comment by m-col** [comment]
It is, but https://github.com/flacjacket/pywlroots/pull/8 fixes this

**Comment by r4dr3fr4d** [comment]
@flacjacket can confirm, are you willing to pull?

**Comment by flacjacket** [comment]
This is now merged, and should be fixed!
