### ISSUE TITLE
`wlroots/_build.py` is installed/packaged only if no existing version is installed

### ISSUE THREAD

**Issue by mgorny** [flacjacket/pywlroots#132]
https://github.com/flacjacket/pywlroots/blob/1b39a33c23e0d0dc0d4fbd60d6e7bd1ca1e17b2d/wlroots/ffi_build.py#L67-L70

This code means that the function won't be executed if `wlroots._build` can be imported from *anywhere*, including the previous version installed to the system. So if pywlroots are installed, the following bit won't ever be executed:

https://github.com/flacjacket/pywlroots/blob/1b39a33c23e0d0dc0d4fbd60d6e7bd1ca1e17b2d/wlroots/ffi_build.py#L86-L87

and the newly created wheel (or install to `--root`) won't contain the file. As a result, the Gentoo ebuild produces an install without the file every second run; which in turns breaks building qtile.

Downstream bug report: https://bugs.gentoo.org/919097

**Comment by mgorny** [comment]
Upon further investigation, this cache logic can't ever work properly!

Even if `wlroots/_build.py` exists in the source, `wlroots._build` cannot be imported because `wlroots` requires `wlroots._ffi` that doesn't exist yet!

```pytb
 python3.11 -c 'import wlroots._build'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/portage/dev-python/pywlroots-0.16.6-r2/work/pywlroots-0.16.6/wlroots/__init__.py", line 8, in <module>
    from ._ffi import ffi, lib
ModuleNotFoundError: No module named 'wlroots._ffi'
```

So the only case when "caching" works is when it wrongly imports the earlier version…
