### ISSUE TITLE
unable to run tiny example (Unable to create a renderer)

### ISSUE THREAD

**Issue by brainwave0** [flacjacket/pywlroots#206]
I'm trying to run the `tiny` example on NixOS, and I'm getting these errors:

```
INFO:wlroots:[backend/wayland/backend.c:572] Creating wayland backend
INFO:wlroots:[render/egl.c:206] Supported EGL client extensions:
ERROR:wlroots:[render/egl.c:209] EGL_EXT_platform_base not supported
ERROR:wlroots:[render/egl.c:524] Failed to create EGL context
ERROR:wlroots:[render/gles2/renderer.c:804] Could not initialize EGL
ERROR:wlroots:[render/wlr_renderer.c:423] Could not initialize renderer
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ian/Sync/projects/code/ftwm/pywlroots/tiny/__main__.py", line 67, in <module>
    main(sys.argv[1:])
  File "/home/ian/Sync/projects/code/ftwm/pywlroots/tiny/__main__.py", line 31, in main
    compositor, allocator, renderer, backend, subcompositor = build_compositor(
                                                              ^^^^^^^^^^^^^^^^^
  File "/home/ian/Sync/projects/code/ftwm/venv/lib/python3.11/site-packages/wlroots/helper.py", line 33, in build_compositor
    renderer = Renderer.autocreate(backend)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/Sync/projects/code/ftwm/venv/lib/python3.11/site-packages/wlroots/renderer.py", line 31, in autocreate
    raise RuntimeError("Unable to create a renderer.")
RuntimeError: Unable to create a renderer.
Segmentation fault (core dumped)
```

Could this be a pywlroots issue, or is it likely something else?

For reference, this is my shell.nix:

```
let pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/9256f7c71a195ebe7a218043d9f93390d49e6884.tar.gz") {};
in
(pkgs.buildFHSUserEnv rec {
  name = "pipzone";
  targetPkgs = pkgs: (with pkgs; [
    expat
    gcc
    glib
    libGL
    libxkbcommon
    libz
    python3Full
    python3Packages.pip
    python3Packages.virtualenv
    wlroots
  ]);
  profile = ''
    export C_INCLUDE_PATH="${pkgs.lib.strings.makeIncludePath (targetPkgs pkgs)}"
    export SUBSHELL_NAME="nix-shell"
    source venv/bin/activate
  '';
}).env
```

**Comment by brainwave0** [comment]
Yes, your solution worked! That `--no-binary :all:` did the trick.
